### ISSUE TITLE
Use SVG only method

### ISSUE THREAD

**Issue by ai** [jonathantneal/postcss-conic-gradient#4]
We should generate a pure SVG, sintead of raster magic iwht PNG

**Comment by jonathantneal** [comment]
I’ll look into it.

**Comment by LeaVerou** [comment]
To do with with the same kind of smoothness in the general case, you would need 720 arcs, i.e. 720 paths or circles with partial strokes. This is why I chose to generate the PNG with `<canvas>`, and it was not an easy choice as I love vectors for almost anything.

**Comment by jonathantneal** [comment]
We’ll stick with JPG for now.
