### ISSUE TITLE
Error on install package

### ISSUE THREAD

**Issue by alexandreogrodovski** [jonathantneal/postcss-conic-gradient#5]
I ran "npm install postcss-conic-gradient --save-dev" but was unable to install the package.

The following message appeared:

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found

**Comment by jonathantneal** [comment]
Yes, this was due to wild requirements that will no longer be necessary in the next version.
