### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by MattDiMu** [jonathantneal/postcss-conic-gradient#7]
I'd really like to use this polyfill, but the installation instructions shock me and I hope I've misunderstood them. Do I really need (on windows 7) to:
- Install (outdated) 2.7.x [Python](https://www.python.org/getit/)
- Install [Visual Studio C++ Express](https://www.visualstudio.com/de-de/products/visual-studio-express-vs)
- Install [node-gyp](https://github.com/TooTallNate/node-gyp/)
- Make sure Python is available in Path
- Install [Windows 7 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=8279) for 64-bit-support
- Install (outdated) [GTK 2](http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+_2.22.1-1_win64.zip)
- build node-gyp
- npm install postcss-conic-gradient --save-dev

Isn't there a simpler way?

**Comment by LeaVerou** [comment]
> Isn't there a simpler way?

Yes, you can use the prefixfree polyfill and not install anything :)

**Comment by jonathantneal** [comment]
The next release will not require this. It just took a few years for amazing people to rewrite canvas in JavaScript and WASM.
